# Python Basic CheatSheet
<img src="../sample_files/logos/python.svg" width="200" height="200" />

## Python File
define coding and python interpreter at the top of the file

In [19]:
#!/usr/bin/python
# -*- coding: utf-8 -*-
# -*- coding: latin1 -*-
# -*- coding: iso-8859-1 -*-
# durch coding auch umlaut möglich

## Asking for Help

In [8]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getatt

## Import
```python
import <modulname>
<modulname>.<modulfunction>

from <modulname> import <function>
<function>
```

In [20]:
import math
math.sqrt(25)
     
from math import sqrt
sqrt(25)
     
from math import *
sqrt(25)
log(10)

import numpy
import numpy as np

## Variables and DataTypes

### Variable Assigments

In [21]:
var_int = 5
var_long = 1.23
var_float = 9.25e-3
var_complex = (5.3 + 3j)
var_bool = True

### Calculation with Variables

In [23]:
ans = x+2  # Sum of two variables
ans = x-2  # Subtraction of two variables
ans = x*2  # Multiplication of two variables
ans = x**2 # Exponentiation of a variable
ans = x%2  # Remainder of a variable
x/float(2) # Division of a variable

2.5

### Types and Type Conversions

In [18]:
int()               # to integer
float()             # to float
complex()           # to complex
long()              # to long
unichr()            # int to 1 char
ord()               # 1 element string to int
str()               # int to string
bool()              # to boolean

NameError: name 'long' is not defined

## Strings

In [24]:
oneline_string_1 = 'String'
oneline_string_2 = "String"
multiline_string = '''Multiline String
on multiple lines'''

### String Operations

In [26]:
my_string = "Awesome String"
ans = my_string * 2
print(ans)
ans = my_string + ' Add'
print(ans)
ans = 'm' in my_string
print(ans)
# index starts at 0
ans = my_string[3]
print(ans)
ans = my_string[4:9]
print(ans)

Awesome StringAwesome String
Awesome String Add
True
s
ome S


### String Methodes

In [12]:
ans = my_string.upper()             # String to uppercase
print(ans)
ans = my_string.lower()             # String to lowercase
print(ans)
ans = my_string.count('w')          # Count String elements
print(ans)
ans = my_string.replace('e', 'i')   # Replace String elements
print(ans)
ans = my_string.strip()             # Strip whitespaces
print(ans)

THISSTRINGISAWESOME
thisstringisawesome
1
thisStringIsAwisomi
thisStringIsAwesome


## Lists

In [28]:
>>> a = 'is'
>>> b = 'nice'
>>> my_list = ['my', 'list', a, b]
>>> my_list2 = [[4,5,6,7], [3,4,5,6]]

### Selecting List Elements

In [31]:
# Subset
my_list[1]      # Select item at index 1
my_list[-3]     # Select 3rd last item
# Slice
my_list[1:3]    # Select item at index 1 and 2
my_list[1:]     # Select items after index 0
my_list[:3]     # Select items before index 3
my_list[:]      # Copy my_list
# Subset Lists of Lists
my_list2[1][0]  # my_list[list][itemOfList]
my_list2[1][:2] #

[3, 4]

### List Operations

In [ ]:
my_list + my_list
my_list* 2
my_list2 > 4

### List Methods

In [39]:
my_list.index(a)      # Get the index of an item
my_list.count(a)      # Count an item
my_list.append("!")   # Append an item at a time
my_list.reverse()     # Reverse tbe list
my_list.extend("!")   # Append an item
my_list.sort()        # Sort the list
my_list.insert(0,"!") # Insert an item
my_list.pop(-1)       # Remove an item
my_list.remove('!')   # Remove an item
del(my_list[0:1])     # Remove an item

## Numpy Arrays

In [41]:
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)
my_2darray = np.array([[1,2,3],[4,5,6]])

### Selecting Numpy Array Elements

In [45]:
# Subset
my_array[1]     # Select item at index 1

# Slice
my_array[0:2]   # Select items at index 0 and 1

# Subset 2D Numpy arrays
my_2darray[:,0]  # my_2darray[rows, columns]

array([1, 4])

### Numpy Array Operations

In [47]:
my_array > 3                   # array([False, False, False, True])
my_array * 2                   # array([2,4,6,8])
my_array + np.array([5,6,7,8]) # array([6,8,10,12])

array([ 6,  8, 10, 12])

### Numpy Array Functions

In [57]:
my_array.shape            # Get the dimensions of the array
np.append(my_array, np.array([5,6,7,8]))  # Append items to an array
np.insert(my_array, 1, 5) # Insert items in an array
np.delete(my_array,[1])   # Delete items in an array
np.mean(my_array)         # Mean of the array
np.median(my_array)       # Median of the array
np.corrcoef(my_array)     # Correlation coefficient
np.std(my_array)          # Standart deviation

1.118033988749895

## Operator Priority

In [1]:
+                   # Plus         3 + 5 = 8 'a' + 'b' = 'ab'
-                   # Minus        -5.2 order 5 - 2
*                   # Multiplcation 2 * 3 = 6
**                  # Power        3 ** 4 = 3 * 3 * 3 * 3 = 81
/                   # Division     4 / 3 = 1 oder 4.0/3 = 1.3333...
//                  # Integer  Division 4 // 3.0 = 1.0
%                   # Modulo       8 % 3 = 2
<<                  # Bitwise left 2 << 2 = 8   (in binary)
>>                  # Bitwise right 11 >> 1 = 5 (in binary)
&                   # Bitwise AND  5 & 3 = 1    (in binary)
¦                   # Bitwise OR   5 | 3 = 7    (in binary)
^                   # Bitwise XOR  5 ^ 3 = 6    (in binary)
~                   # Bitwise NOT  ~5 = -6
<                   # Smaller as
>                   # Bigger as
<=                  # Smaller Equal
>=                  # Bigger Equal
==                  # Equal
!=                  # Not Equal
not                 # log NOT
and                 # log AND
or                  # log OR

SyntaxError: invalid syntax (<ipython-input-1-03af7eef6ce2>, line 1)

## Range and Linspace

In [14]:
print("range(start=1,stop=5,step=2) = {}".format(list(range(1,5,2))))
print("range(1,5)                   = {}".format(list(range(1,5))))
print("range(0,5)                   = {}".format(list(range(0,5))))

range(start=1,stop=5,step=2) = [1, 3]
range(1,5)                   = [1, 2, 3, 4]
range(0,5)                   = [0, 1, 2, 3, 4]


In [25]:
import numpy as np
print("np.linspace(start = 0, stop = 100, num = 5, dtype = int) = {}".format(np.linspace(0,100,5,int)))
print("np.linspace(0, 100, 7) = {}".format(np.linspace(0,100,5,int)))
print("np.linspace(0, 99.999999999999, 3, int) = {}".format(np.linspace(0, 99.99999999, 3)))

np.linspace(0, 100, 3, int)


np.linspace(start = 0, stop = 100, num = 5, dtype = int) = [  0.  25.  50.  75. 100.]
np.linspace(0, 100, 7) = [  0.  25.  50.  75. 100.]
np.linspace(0, 99.999999999999, 3, int) = [ 0.         50.         99.99999999]


array([  0.,  50., 100.])