# Python SciPy Linear Algebra CheatSheet
<img src="../sample_files/logos/scipy.svg" width="150" />
The SciPy library is one of the core packages for scientific computing that provides mathematical algorithms and convenience functions built on the NumPy extension of Python.

## Asking for Help

In [ ]:
help(scipy.linalg.diagsvd)
np.info(np.matrix)

## Interacting with NumPy

In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1+5j,2j,3j), (4j,5j,6j)])
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])

### Index Tricks

In [8]:
ans = np.mgrid[0:5,0:5]       # Create a dense meshgrid
print("np.mgrid[0:5,0:5] = \n{}".format(ans))
ans = np.ogrid[0:2,0:2]       # Create an open meshgrid
print("np.ogrid[0:2,0:2] = \n{}".format(ans))
ans = np.r_[3,[0]*5,-1:1:10j] # Stack arrays vertically (row-wise)
print("np.r_[3,[0]*5,-1:1:10j] = \n{}".format(ans))
#np.c_[b,c]              # Create stacked column-wise arrays

np.mgrid[0:5,0:5] = 
[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
np.ogrid[0:2,0:2] = 
[array([[0],
       [1]]), array([[0, 1]])]
np.r_[3,[0]*5,-1:1:10j] = 
[ 3.          0.          0.          0.          0.          0.
 -1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


### Shape Manipulation

In [14]:
ans = np.transpose(b)  # Permute array dimensions
print("np.transpose(b) = \n{}".format(ans))
b.flatten()      # Flatten the array
print("b.flatten() = \n{}".format(ans))
#ans = np.hstack((b,c)) # Stack arrays horizontally (column-wise)
#print("np.hstack((b,c)) = \n{}".format(ans))
ans = np.vstack((a,b)) # Stack arrays vertically (row-wise)
print("np.vstack((a,b)) = \n{}".format(ans))
ans = np.hsplit(c,2)   # Split the array horizontally at the 2nd index
print("np.hsplit(c,2) = \n{}".format(ans))
ans = np.vsplit(c,2)   # Split the array vertically at the 2nd index
print("np.vsplit(c,2) = \n{}".format(ans))

np.transpose(b) = 
[[1.+5.j 0.+4.j]
 [0.+2.j 0.+5.j]
 [0.+3.j 0.+6.j]]
b.flatten() = 
[[1.+5.j 0.+4.j]
 [0.+2.j 0.+5.j]
 [0.+3.j 0.+6.j]]
np.vstack((a,b)) = 
[[1.+0.j 2.+0.j 3.+0.j]
 [1.+5.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
np.hsplit(c,2) = 
[array([[[1.5, 2. , 3. ]],

       [[3. , 2. , 1. ]]]), array([[[4., 5., 6.]],

       [[4., 5., 6.]]])]
np.vsplit(c,2) = 
[array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
        [4., 5., 6.]]])]


### Polynomials
$p = 3x^2+4x+5$

In [16]:
from numpy import poly1d
p = poly1d([3,4,5]) # Create a polynomial object
print(p)

   2
3 x + 4 x + 5


### Vectorizing Functions
Define a vectorized function which takes a nested sequence of objects or numpy arrays as inputs and returns an single or tuple of numpy array as output.

In [23]:
def func(a):
  if a < 0:
    return a*2
  else:
    return a/2
vectorized_func = np.vectorize(myfunc) # Vectorize functions
vectorized_func([1, 2, 3])
vectorized_func(a)

array([0.5, 1. , 1.5])

### Type Handling

In [24]:
ans = np.real(b)                   # Return the real part of the array elements
print("np.real(b) = \n{}".format(ans))
ans = np.imag(b)                   # Return the imaginary part of the array elements
print("np.imag(b) = \n{}".format(ans))
ans = np.real_if_close(c,tol=1000) # Return a real array if complex parts close to 0
print("np.real_if_close(c,tol=1000) = \n{}".format(ans))
ans = np.cast['f'](np.pi)          # Cast object to a data type
print("np.cast['f'](np.pi) = \n{}".format(ans))

np.real(b) = 
[[1. 0. 0.]
 [0. 0. 0.]]
np.imag(b) = 
[[5. 2. 3.]
 [4. 5. 6.]]
np.real_if_close(c,tol=1000) = 
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
np.cast['f'](np.pi) = 
3.1415927410125732


### Other Useful Functions

In [39]:
import scipy
ans = np.angle(b,deg=True)     # Return the angle of the complex argument
print("np.angle(b,deg=True) =\n{}".format(ans))
g = np.linspace(0,np.pi,num=5) # Create an array of evenly spaced values
print("np.linspace(0,np.pi,num=5) =\n{}".format(g))
g[3:] += np.pi                 # (number of samples)
print("g[3:] += np.pi  =\n{}".format(g))
ans = np.unwrap(g)                   # Unwrap
print("np.unwrap(g) =\n{}".format(g))
ans = np.logspace(0,10,3)            # Create an array of evenly spaced values (log scale)
print("np.logspace(0,10,3) =\n{}".format(g))
ans = np.select([c<4],[c*2])         # Return values from a list of arrays depending on conditions
print("np.select([c<4],[c*2]) =\n{}".format(g))
ans = scipy.special.factorial(a)              # Factorial
print("scipy.special.factorial(a) =\n{}".format(g))
ans = scipy.special.comb(10,3,exact=True)     # Combine N things taken at k time
print("scipy.special.comb(10,3,exact=True) =\n{}".format(g))
ans = scipy.misc.central_diff_weights(3)   # Weights for Np-point central derivative
print("scipy.misc.central_diff_weights(3) =\n{}".format(g))
ans = scipy.misc.derivative(myfunc,1.0)    # Find the n-th derivative of a function at a point
print("scipy.misc.derivative(myfunc,1.0) =\n{}".format(g))

np.angle(b,deg=True) =
[[78.69006753 90.         90.        ]
 [90.         90.         90.        ]]
np.linspace(0,np.pi,num=5) =
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
g[3:] += np.pi  =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]
np.unwrap(g) =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]
np.logspace(0,10,3) =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]
np.select([c<4],[c*2]) =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]
misc.factorial(a) =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]
misc.comb(10,3,exact=True) =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]
misc.central_diff_weights(3) =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]
misc.derivative(myfunc,1.0) =
[0.         0.78539816 1.57079633 5.49778714 6.28318531]


## Linear Algebra
You’ll use the`linalg` and `sparse` modules. Note that `scipy.linalg` contains and expands on `numpy.linalg`.

In [43]:
from scipy import linalg, sparse

### Creating Matrices

In [46]:
A = np.matrix(np.random.random((2,2)))
B = np.asmatrix(b)
C = np.mat(np.random.random((10,5)))
D = np.mat([[3,4], [5,6]])
print(" A=\n{}\nB=\n{}\nC=\n{}\nD=\n{}".format(A,B,C,D))

 A=
[[0.41535575 0.05248234]
 [0.59596127 0.26570118]]
B=
[[1.+5.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
C=
[[0.87196631 0.85059865 0.43109014 0.72926946 0.05504349]
 [0.1267211  0.66255714 0.65928221 0.53978017 0.86726603]
 [0.59678061 0.41680812 0.23374995 0.83862778 0.30799501]
 [0.5163074  0.5755012  0.96140432 0.21797779 0.12238564]
 [0.03612404 0.21578817 0.85761329 0.02176608 0.2995802 ]
 [0.03107766 0.14341377 0.19893061 0.38395095 0.28332364]
 [0.98536908 0.50471775 0.45862977 0.94852765 0.24265192]
 [0.30727293 0.12903476 0.36659723 0.00309417 0.64608388]
 [0.90171263 0.23402267 0.61745369 0.42015993 0.3112721 ]
 [0.01780881 0.58215475 0.54080491 0.28480372 0.69636211]]
D=
[[3 4]
 [5 6]]


### Basic Matrix Routines

In [58]:
# Inverse Matrix A^-1
ans = A.I                    # Inverse 
print("A.I = \n{}".format(ans))
ans = linalg.inv(A)          # Inverse
print("linalg.inv(A) = \n{}".format(ans))

# Transposition
# Permute the dimensions of an array.
ans = A.T                    # Transpose matrix
print("A.T = \n{}".format(ans))
ans = A.H                    # Conjugate transposition
print("A.H = \n{}".format(ans))

# Trace
# Return the sum along diagonals of the array
ans = np.trace(A)            # Trace
print("np.trace(A) = \n{}".format(ans))

# Norm
ans = linalg.norm(A)        # Frobenius norm
print("linalg.norm(A) =\n{}".format(ans))
ans = linalg.norm(A,1)      # L1 norm (max column sum)
print("linalg.norm(A,1) =\n{}".format(ans))
ans = linalg.norm(A,np.inf) # L inf norm (max row sum)
print("linalg.norm(A,np.inf) =\n{}".format(ans))

# Rank
# The number of linearly independent columns in a matrix is the rank of the matrix. The row and column rank of a matrix are always equal.
ans = np.linalg.matrix_rank(C) # Matrix rank
print("np.linalg.matrix_rank(C) =\n{}".format(ans))

# Determinant
# The determinant of a matrix is denoted, or. Geometrically, it can be viewed as the scaling factor of the linear transformation described by the matrix.
ans = linalg.det(A) # Determinant
print("linalg.det(A) =\n{}".format(ans))

# Solving linear problems
# Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:
ans = np.linalg.solve(np.array([[3,1], [1,2]]), np.array([9,8]))
print("np.linalg.solve(np.array([[3,1], [1,2]]), np.array([9,8])) =\n{}".format(ans))
E = np.mat(a).T   # Solver for dense matrices
print("np.mat(a).T =\n{}".format(E))
ans = linalg.lstsq(A,D) # Least-squares solution to linear matrix equation
print("linalg.lstsq(A,D) =\n{}".format(ans))

# Generalized inverse
ans = linalg.pinv(C)    # Compute the pseudo-inverse of a matrix (least-squares solver)
print("linalg.pinv(C) =\n{}".format(ans))
ans = linalg.pinv2(C)   # Compute the pseudo-inverse of a matrix (SVD)
print("linalg.pinv2(C) =\n{}".format(ans))

A.I = 
[[ 3.35977324 -0.66363561]
 [-7.53588939  5.25214491]]
linalg.inv(A) = 
[[ 3.35977324 -0.66363561]
 [-7.53588939  5.25214491]]
A.T = 
[[0.41535575 0.59596127]
 [0.05248234 0.26570118]]
A.H = 
[[0.41535575 0.59596127]
 [0.05248234 0.26570118]]
np.trace(A) = 
0.6810569292256414
linalg.norm(A) =
0.7752688223920543
linalg.norm(A,1) =
1.011317016602859
linalg.norm(A,np.inf) =
0.8616624544177166
np.linalg.matrix_rank(C) =
5
linalg.det(A) =
0.07908307039182563
np.linalg.solve(np.array([[3,1], [1,2]]), np.array([9,8])) =
[2. 3.]
np.mat(a).T =
[[1]
 [2]
 [3]]
linalg.lstsq(A,D) =
(array([[6.76114169, 9.45727932],
       [3.65305639, 1.36931192]]), array([], dtype=float64), 2, array([0.76840718, 0.10291818]))
linalg.pinv(C) =
[[ 3.25500467e-01 -3.43200596e-01 -1.86174769e-01 -1.41061662e-02
  -4.68316297e-01 -5.23240832e-01  9.06819243e-02  7.84606771e-01
   6.47016110e-01 -1.47886246e-01]
 [ 1.23676944e+00  2.44079438e-01 -3.85736987e-01  3.10134581e-01
  -6.35646342e-01 -6.16592552e-01 -

### Creating Sparse Matrices

In [63]:
F = np.eye(3, k=1)         # Create a 2X2 identity matrix
print("np.eye(3, k=1) = \n{}".format(F))
G = np.mat(np.identity(2)) # Create a 2x2 identity matrix
print("np.mat(np.identity(2)) = \n{}".format(G))
C[C > 0.5] = 0
print("C[C > 0.5] = 0 = \n{}".format(C))
H = sparse.csr_matrix(C)   # Compressed Sparse Row matrix
print("np.mat(np.identity(2)) = \n{}".format(H))
I = sparse.csc_matrix(D)   # Compressed Sparse Column matrix
print("sparse.csc_matrix(D) = \n{}".format(I))
J = sparse.dok_matrix(A)   # Dictionary Of Keys matrix
print("sparse.dok_matrix(A) = \n{}".format(J))
K = sparse.isspmatrix_csc(A)   # Identify sparse matrix
print("sparse.isspmatrix_csc(A) = \n{}".format(K))

np.eye(3, k=1) = 
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
np.mat(np.identity(2)) = 
[[1. 0.]
 [0. 1.]]
C[C > 0.5] = 0 = 
[[0.         0.         0.43109014 0.         0.05504349]
 [0.1267211  0.         0.         0.         0.        ]
 [0.         0.41680812 0.23374995 0.         0.30799501]
 [0.         0.         0.         0.21797779 0.12238564]
 [0.03612404 0.21578817 0.         0.02176608 0.2995802 ]
 [0.03107766 0.14341377 0.19893061 0.38395095 0.28332364]
 [0.         0.         0.45862977 0.         0.24265192]
 [0.30727293 0.12903476 0.36659723 0.00309417 0.        ]
 [0.         0.23402267 0.         0.42015993 0.3112721 ]
 [0.01780881 0.         0.         0.28480372 0.        ]]
np.mat(np.identity(2)) = 
  (0, 2)	0.4310901356869927
  (0, 4)	0.05504348641515677
  (1, 0)	0.12672110454944197
  (2, 1)	0.4168081155065665
  (2, 2)	0.23374994673709137
  (2, 4)	0.3079950139772445
  (3, 3)	0.2179777878151511
  (3, 4)	0.12238564052707224
  (4, 0)	0.0361240359671372
  (4, 1)	0.21578816

### Sparse Matrix Routines

In [80]:
import scipy.sparse.linalg as la
# Inverse
ans = la.inv(I)
print("la.inv(I) = \n{}".format(ans))
# Norm
ans = la.norm(I)
print("la.norm(I) = \n{}".format(ans))

# Solving linear problems
la.spsolve(H,I) # Solver for sparse matrices

la.inv(I) = 
  (0, 0)	-3.0000000000000044
  (1, 0)	2.5000000000000036
  (0, 1)	2.0000000000000027
  (1, 1)	-1.5000000000000022
la.norm(I) = 
9.273618495495704


ValueError: matrix must be square (has shape (10, 5))

### Matrix Functions

In [84]:
# Addition
ans = np.add(A,D)
print("np.add(A,D) =\n{}".format(ans))

# Subtraction
ans = np.subtract(A,D)
print("np.subtract(A,D) =\n{}".format(ans))

# Division
ans = np.divide(A,D)
print("np.divide(A,D) =\n{}".format(ans))

# Multiplication
ans = A @ D             # Multiplication operator
print("A @ D =\n{}".format(ans))
ans = np.multiply(D,A)  # Multiplication
print("np.multiply(D,A) =\n{}".format(ans))
ans = np.dot(A,D)       # Dot product
print("np.dot(A,D) =\n{}".format(ans))
ans = np.vdot(A,D)      # Vector dot product
print("np.vdot(A,D) =\n{}".format(ans))
ans = np.inner(A,D)     # Inner product
print("np.inner(A,D) =\n{}".format(ans))
ans = np.outer(A,D)     # Outer product
print("np.outer(A,D) =\n{}".format(ans))
ans = np.tensordot(A,D) # Tensor dot product
print("np.tensordot(A,D) =\n{}".format(ans))
ans = np.kron(A,D)      # Kronecker product
print("np.kron(A,D) =\n{}".format(ans))

# Exponential Functions
ans = linalg.expm(A)    # Matrix exponential
print("linalg.expm(A) =\n{}".format(ans))
ans = linalg.expm2(A)   # Matrix exponential (Taylor Series)
print("linalg.expm2(A) =\n{}".format(ans))
ans = linalg.expm3(D)   # Matrix exponential (eigenvalue decomposition)
print("linalg.expm3(D) =\n{}".format(ans))

# Logarithm Function
ans = linalg.logm(A)    # Matrix logarithm
print("linalg.logm(A) =\n{}".format(ans))

# Trigonometric Functions
ans = linalg.sinm(D)    # Matrix sine
print("linalg.sinm(D) =\n{}".format(ans))
ans = linalg.cosm(D)    # Matrix cosine
print("linalg.cosm(D) =\n{}".format(ans))
ans = linalg.tanm(A)    # Matrix tangent
print("linalg.tanm(A) =\n{}".format(ans))

# Hyperbolic Trigonometric Functions
ans = linalg.sinhm(D)   # Hypberbolic matrix sine
print("linalg.sinhm(D) =\n{}".format(ans))
ans = linalg.coshm(D)   # Hyperbolic matrix cosine
print("linalg.coshm(D) =\n{}".format(ans))
ans = linalg.tanhm(A)   # Hyperbolic matrix tangent
print("linalg.tanhm(A) =\n{}".format(ans))

# Matrix Sign Function
ans = np.signm(A)       # Matrix sign function
print("np.signm(A) =\n{}".format(ans))

# Matrix Square Root
ans = linalg.sqrtm(A)   # Matrix square root
print("linalg.sqrtm(A) =\n{}".format(ans))

# Arbitrary Functions
ans = linalg.funm(A, lambda x: x*x) # Evaluate matrix function
print("linalg.funm(A, lambda x: x*x) =\n{}".format(ans))

np.add(A,D) =
[[3.41535575 4.05248234]
 [5.59596127 6.26570118]]
np.subtract(A,D) =
[[-2.58464425 -3.94751766]
 [-4.40403873 -5.73429882]]
np.divide(A,D) =
[[0.13845192 0.01312059]
 [0.11919225 0.04428353]]
A @ D =
[[1.50847894 1.97631703]
 [3.11638973 3.97805218]]
np.multiply(D,A) =
[[1.24606724 0.20992937]
 [2.97980635 1.5942071 ]]
np.dot(A,D) =
[[1.50847894 1.97631703]
 [3.11638973 3.97805218]]
np.vdot(A,D) =
[[1.24606724]]
np.inner(A,D) =
[[1.4559966  2.39167278]
 [2.85068855 4.57401346]]
np.outer(A,D) =
[[1.24606724 1.66142298 2.07677873 2.49213447]
 [0.15744702 0.20992937 0.26241171 0.31489405]
 [1.78788381 2.38384508 2.97980635 3.57576763]
 [0.79710355 1.06280473 1.32850592 1.5942071 ]]
np.tensordot(A,D) =
6.030010057946554
np.kron(A,D) =
[[1.24606724 1.66142298 0.15744702 0.20992937]
 [2.07677873 2.49213447 0.26241171 0.31489405]
 [1.78788381 2.38384508 0.79710355 1.06280473]
 [2.97980635 3.57576763 1.32850592 1.5942071 ]]
linalg.expm(A) =
[[1.53752016 0.07422817]
 [0.84289526 

AttributeError: module 'scipy.linalg' has no attribute 'expm2'

### Sparse Matrix Functions

In [85]:
import scipy.sparse.linalg as la
ans = la.expm(I)  # Sparse matrix exponential
print("la.expm(I) = \n{}".format(ans))

la.expm(I) = 
  (0, 0)	3433.286387715417
  (1, 0)	5334.926198416135
  (0, 1)	4267.940958732908
  (1, 1)	6634.242106765096


### Decompositions

In [89]:
# Eigenvalues and Eigenvectors
la, v = linalg.eig(A)  # Solve ordinary or generalized eigenvalue problem for square matrix
l1, l2 = la            # Unpack eigenvalues
v[:,0]                 # First eigenvector
v[:,1]                 # Second eigenvector
linalg.eigvals(A)      # Unpack eigenvalues

# Singular Value Decomposition
U,s,Vh = linalg.svd(B) # Singular Value Decomposition (SVD)
M,N = B.shape
Sig = linalg.diagsvd(s,M,N) # Construct sigma matrix in SVD

# LU Decomposition
P,L,U = linalg.lu(C)   # LU Decomposition

### Sparse Matrix Decompositions

In [86]:
la, v = sparse.linalg.eigs(F,1) # Eigenvalues and eigenvectors
sparse.linalg.svds(H, 2)        # SVD

(array([[ 0.44001248, -0.25579124],
        [ 0.03204192, -0.01281122],
        [ 0.07377719, -0.45971824],
        [-0.22641168, -0.1513002 ],
        [-0.14182631, -0.26337639],
        [-0.22859448, -0.46895281],
        [ 0.41286903, -0.37283353],
        [ 0.43805927, -0.2764587 ],
        [-0.50470031, -0.42767844],
        [-0.24332635, -0.11201402]]),
 array([0.69491042, 1.05561098]),
 array([[ 0.1757108 , -0.13559093,  0.73592414, -0.60469442, -0.20856925],
        [-0.10671994, -0.42767775, -0.5526267 , -0.40850125, -0.57743663]]))