# Gram-Schmidt
[Gram-Schmidt orthogonalization](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process) is a method used in linear algebra to produce an orthogonal [or orthonormal] base that generates the same vector space as a [inear span](https://en.wikipedia.org/wiki/Linear_span) of a given set of vectors.

The algorithm is easy to understand if you are familiar with linear algebra. If you are not, here’s an intuitive explanation.

It’s right noon and Sun is at the highest point on the sky. There is a column in front of you throwing a **shadow** on the **floor**. The shadow indicates that the column is not **perpendicular** to the floor. Therefore you slightly push the column until shadow disappears.

In terms of linear algebra:

* floor ~ vector space
* shadow ~ projection
* perpendicular ~ orthogonal
* pushing until shadow disappears ~ Gram-Schmidt process

Gram-Schmidt also gives us [QR decomposition](https://en.wikipedia.org/wiki/QR_decomposition) for free. It is a process of decomposing matrix X into a product of two matrices, `X = QR`, where Q is an orthogonal matrix and R is upper triangular matrix.

In [1]:
import numpy as np

## algorithm

In [2]:
def gram_schmidt(X):
    O = np.zeros(X.shape)

    for i in range(X.shape[1]):
        # orthogonalization
        vector = X[:, i]
        space = O[:, :i]
        projection = vector @ space
        vector = vector - np.sum(projection * space, axis=1)

        # normalization
        norm = np.sqrt(vector @ vector)
        vector /= abs(norm) < 1e-8 and 1 or norm
        
        O[:, i] = vector

    return O

## run

In [3]:
# 6 column vectors in 4D
vectors = np.array([
    [1, 1, 2, 0, 1, 1],
    [0, 0, 0, 1, 2, 1],
    [1, 2, 3, 1, 3, 2],
    [1, 0, 1, 0, 1, 1]
], dtype=float)

In [4]:
# check orthogonality
vectors.T @ vectors

array([[ 3.,  3.,  6.,  1.,  5.,  4.],
       [ 3.,  5.,  8.,  2.,  7.,  5.],
       [ 6.,  8., 14.,  3., 12.,  9.],
       [ 1.,  2.,  3.,  2.,  5.,  3.],
       [ 5.,  7., 12.,  5., 15., 10.],
       [ 4.,  5.,  9.,  3., 10.,  7.]])

In [5]:
orthonormal = gram_schmidt(vectors)
orthonormal.round(5)

array([[ 0.57735, -0.     , -0.     , -0.30861,  0.     , -0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.92582,  0.     ,  0.     ],
       [ 0.57735,  0.70711,  0.     ,  0.1543 ,  0.     ,  0.     ],
       [ 0.57735, -0.70711, -0.     ,  0.1543 , -0.     , -0.     ]])

In [6]:
# check orthogonality
(orthonormal.T @ orthonormal).round(5)

array([[ 1., -0., -0., -0.,  0., -0.],
       [-0.,  1.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0.,  0.]])

## QR decomposition

In [7]:
matrix = np.array([
    [1, 1, -1],
    [1, 2, 1],
    [1, 3, 0]
], dtype=float)

In [8]:
Q = gram_schmidt(matrix)
Q.round(5)

array([[ 0.57735, -0.70711, -0.40825],
       [ 0.57735, -0.     ,  0.8165 ],
       [ 0.57735,  0.70711, -0.40825]])

In [9]:
R = Q.T @ matrix
R.round(5)

array([[ 1.73205,  3.4641 ,  0.     ],
       [-0.     ,  1.41421,  0.70711],
       [ 0.     ,  0.     ,  1.22474]])

In [10]:
(Q @ R).round(5)

array([[ 1.,  1., -1.],
       [ 1.,  2.,  1.],
       [ 1.,  3., -0.]])